<a href="https://colab.research.google.com/github/jelly12paw/o_o/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.tree import DecisionTreeClassifier # 의사결정나무
from sklearn.model_selection import train_test_split # 데이터셋 분류기
from sklearn.metrics import accuracy_score # 모델 성능 측정
from sklearn.metrics import confusion_matrix # 모델 성능 측정 - 오차 행렬
from sklearn.metrics import classification_report # 평가지표 계산
from sklearn.preprocessing import LabelEncoder # 레이블 인코더
from sklearn.neighbors import KNeighborsClassifier # KNN
from sklearn.preprocessing import MinMaxScaler # 최소최대 정규화
from sklearn import svm # 서포트벡터머신
from sklearn.linear_model import LogisticRegression # 로지스틱 회귀분석
from sklearn.ensemble import RandomForestClassifier # 랜덤포레스트 (분류)

In [2]:
df = pd.read_csv('http://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
df.groupby('species').size()

species
setosa        50
versicolor    50
virginica     50
dtype: int64

In [6]:
# 데이터 전처리 : 붓꽃 종류를 숫자로 변경

df['species'].replace({'setosa' : 0, 'versicolor' : 1, 'virginica' : 2 }, inplace = True)

df.groupby('species').size()

species
0    50
1    50
2    50
dtype: int64

In [7]:
# 분석 데이터셋 : train_test_split(x, y, test_size = 0.2, random_state = 11)

x = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 11)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


**의사결정나무 (분류)**

In [8]:
# 지도학습 - 의사결정나무 : DecisionTreeClassfier(random_state = 11)

dt = DecisionTreeClassifier(random_state = 11)

dt.fit(x_train, y_train) # 학습 수행

pred = dt.predict(x_test) # 예측 수행

acc = accuracy_score(y_test, pred) # 정확도 측정

print(acc)

0.9333333333333333


In [9]:
# 오차 행렬 - confusion_matrix(y_test, pred)

print(confusion_matrix(y_test, pred))

[[ 9  0  0]
 [ 0 10  0]
 [ 0  2  9]]


In [10]:
# 평가 지표 계산 - classification_report(y_test, pred)

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.83      1.00      0.91        10
           2       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30



In [11]:
df = pd.read_csv('http://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [13]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [14]:
# 데이터 전처리 - Age 컬럼 결측치를 평균값으로 대체 : fillna()
#                 Embarked 컬럼 결측치를 최빈값으로 대체 : mode()[0]
#                 Cabin 컬럼 제외 : drop()

age_mean = df['Age'].mean()
df['Age'].fillna(age_mean, inplace = True)

em_mode = df['Embarked'].mode()[0]
df['Embarked'].fillna(em_mode, inplace = True)

df.drop(['Cabin'], axis = 1, inplace = True)

df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare Embarked  
0        1      0         A/5 21171   7.2500        S  
1        1      0          PC 17599  71.2833        C  
2        0      0  STON/O2. 3101282   7.9250        S  
3        1      0            113803  53.1000        S  
4        0      0            373450   8.0500        S  
..     ...    ...               ...      ...      ...  
886      0      0            211536  13.0000        S  
887      0      0            112053  30.0000        S  
888      1      2        W./C. 6607  23.4500        S  
889      0      0            111369  30.0000        C  
890      0      0            370376   7.7500        Q  

[891 rows x 11 columns]

In [15]:
# 데이터 전처리 - 레이블 인코더 : LabelEncoder().fit_transform()
#                 카테고리 컬럼의 값을 숫자 값으로 변환

df['Sex'] = LabelEncoder().fit_transform(df['Sex'])

df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'])

df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.000000      1   
2                               Heikkinen, Miss. Laina    0  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.000000      1   
4                             Allen, Mr. William Henry    1  35.000000      0   
..                                                 ...  ...        ...    ...   
886                              Montvila, Rev. Juozas    1  27.000000      0   
887                       Graham, Miss. Margaret Edith    0  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"    0  29.699118      1   
889                              Behr, Mr. Karl Howell    1  26.000000      0   
890                                Dooley, Mr. Patrick    1  32.000000      0   

     Parch            Ticket     Fare  Embarked  
0        0         A/5 21171   7.2500         2  
1        0          PC 17599  71.2833         0  
2        0  STON/O2. 3101282   7.9250         2  
3        0            113803  53.1000         2  
4        0            373450   8.0500         2  
..     ...               ...      ...       ...  
886      0            211536  13.0000         2  
887      0            112053  30.0000         2  
888      2        W./C. 6607  23.4500         2  
889      0            111369  30.0000         0  
890      0            370376   7.7500         1  

[891 rows x 11 columns]

In [16]:
# 파생변수 추가

df['FamilySize'] = df['SibSp'] + df['Parch']

df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.000000      1   
2                               Heikkinen, Miss. Laina    0  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.000000      1   
4                             Allen, Mr. William Henry    1  35.000000      0   
..                                                 ...  ...        ...    ...   
886                              Montvila, Rev. Juozas    1  27.000000      0   
887                       Graham, Miss. Margaret Edith    0  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"    0  29.699118      1   
889                              Behr, Mr. Karl Howell    1  26.000000      0   
890                                Dooley, Mr. Patrick    1  32.000000      0   

     Parch            Ticket     Fare  Embarked  FamilySize  
0        0         A/5 21171   7.2500         2           1  
1        0          PC 17599  71.2833         0           1  
2        0  STON/O2. 3101282   7.9250         2           0  
3        0            113803  53.1000         2           1  
4        0            373450   8.0500         2           0  
..     ...               ...      ...       ...         ...  
886      0            211536  13.0000         2           0  
887      0            112053  30.0000         2           0  
888      2        W./C. 6607  23.4500         2           3  
889      0            111369  30.0000         0           0  
890      0            370376   7.7500         1           0  

[891 rows x 12 columns]

In [17]:
# 분석 데이터셋

x = df[['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'FamilySize']]
y = df['Survived']

# 분석 데이터셋 분할

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 11)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 6)
(179, 6)
(712,)
(179,)


In [19]:
# 의사결정나무(분류)

dt = DecisionTreeClassifier(random_state = 11)

dt.fit(x_train, y_train)

pred = dt.predict(x_test)

acc = accuracy_score(pred, y_test)

print(acc)

0.7877094972067039


**KNN**

In [21]:
df = pd.read_csv('http://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')

In [24]:
# 4개의 독립변수에 대해 최소 최대 정규화

mm = MinMaxScaler()

df[['sepal_length']] = mm.fit_transform(df[['sepal_length']])
df[['sepal_width']] = mm.fit_transform(df[['sepal_width']])
df[['petal_length']] = mm.fit_transform(df[['petal_length']])
df[['petal_width']] = mm.fit_transform(df[['petal_width']])

df

sepal_length  sepal_width  petal_length  petal_width    species
0        0.222222     0.625000      0.067797     0.041667     setosa
1        0.166667     0.416667      0.067797     0.041667     setosa
2        0.111111     0.500000      0.050847     0.041667     setosa
3        0.083333     0.458333      0.084746     0.041667     setosa
4        0.194444     0.666667      0.067797     0.041667     setosa
..            ...          ...           ...          ...        ...
145      0.666667     0.416667      0.711864     0.916667  virginica
146      0.555556     0.208333      0.677966     0.750000  virginica
147      0.611111     0.416667      0.711864     0.791667  virginica
148      0.527778     0.583333      0.745763     0.916667  virginica
149      0.444444     0.416667      0.694915     0.708333  virginica

[150 rows x 5 columns]

In [25]:
x = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df[['species']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 11)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120, 1)
(30, 1)


In [26]:
# KNN 알고리즘으로 붓꽃 분류

knn = KNeighborsClassifier(n_neighbors = 3) # n_neighbors 값은 홀수로 설정 3, 6, 9로 변경하여 예측값 비교
knn.fit(x_train, y_train)

pred = knn.predict(x_test)

acc = accuracy_score(y_test, pred)

print(acc)

0.9333333333333333


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [27]:
knn = KNeighborsClassifier(n_neighbors = 6) 
knn.fit(x_train, y_train)

pred = knn.predict(x_test)

acc = accuracy_score(y_test, pred)

print(acc)

0.9333333333333333


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [29]:
knn = KNeighborsClassifier(n_neighbors = 9) 
knn.fit(x_train, y_train)

pred = knn.predict(x_test)

acc = accuracy_score(y_test, pred)

print(acc)

0.9333333333333333


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [35]:
# KNN 알고리즘을 이용하여 타이타닉 생존율 예측하기

df = pd.read_csv('http://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

age_mean = df['Age'].mean()
df['Age'].fillna(age_mean, inplace = True)

em_mode = df['Embarked'].mode()[0]
df['Embarked'].fillna(em_mode, inplace = True)

df.drop(['Cabin'], axis = 1, inplace = True)

df['Sex'] = LabelEncoder().fit_transform(df['Sex'])

df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'])

df['FamilySize'] = df['SibSp'] + df['Parch']

x = df[['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'FamilySize']]
y = df['Survived']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 11)

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train, y_train)

pred = knn.predict(x_test)

acc = accuracy_score(y_test, pred)

print('정확도 :', acc)

# 오차 행렬

mat = confusion_matrix(y_test, pred)
print(mat)

# 평가지표 계산

rpt = classification_report(y_test, pred)
print(rpt)

정확도 : 0.7094972067039106
[[96 22]
 [30 31]]
              precision    recall  f1-score   support

           0       0.76      0.81      0.79       118
           1       0.58      0.51      0.54        61

    accuracy                           0.71       179
   macro avg       0.67      0.66      0.67       179
weighted avg       0.70      0.71      0.70       179



**SVM**

In [37]:
df = pd.read_csv('http://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [39]:
# 데이터 전처리

age_mean = df['Age'].mean()
df['Age'].fillna(age_mean, inplace = True)

em_mode = df['Embarked'].mode()[0]
df['Embarked'].fillna(em_mode, inplace = True)

df.drop(['Cabin'], axis = 1, inplace = True)

df['FamilySize'] = df['SibSp'] + df['Parch']

df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  FamilySize  
0      0         A/5 21171   7.2500        S           1  
1      0          PC 17599  71.2833        C           1  
2      0  STON/O2. 3101282   7.9250        S           0  
3      0            113803  53.1000        S           1  
4      0            373450   8.0500        S           0

In [41]:
# 데이터 전처리 - 원 핫 인코더 : pd.get_dummies()

one_s = pd.get_dummies(df['Sex'])
df = pd.concat([df, one_s], axis = 1)

one_e = pd.get_dummies(df['Embarked'])
df = pd.concat([df, one_e], axis = 1)

df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  FamilySize  female  male  C  Q  \
0      0         A/5 21171   7.2500        S           1       0     1  0  0   
1      0          PC 17599  71.2833        C           1       1     0  1  0   
2      0  STON/O2. 3101282   7.9250        S           0       1     0  0  0   
3      0            113803  53.1000        S           1       1     0  0  0   
4      0            373450   8.0500        S           0       0     1  0  0   

   S  
0  1  
1  0  
2  1  
3  1  
4  1

In [43]:
# 훈련셋과 테스트셋 비율을 7 : 3

x = df[['Pclass', 'Age', 'Fare', 'FamilySize', 'female', 'male', 'C', 'Q', 'S']]
y = df['Survived']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 10)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(623, 9)
(268, 9)
(623,)
(268,)


In [48]:
# 소프트벡터머신으로 타이타닉 생존율 분석 : svm.SVC(kernel = 'rbf)

sv = svm.SVC(kernel = 'rbf')
sv.fit(x_train, y_train)

pred = sv.predict(x_test)

acc = accuracy_score(y_test, pred)

print(acc)

0.7238805970149254


In [49]:
# 모델 성능 평가 - 오차 행렬 / 평가지표 계산

print(confusion_matrix(y_test, pred))

print(classification_report(y_test, pred))

[[167   7]
 [ 67  27]]
              precision    recall  f1-score   support

           0       0.71      0.96      0.82       174
           1       0.79      0.29      0.42        94

    accuracy                           0.72       268
   macro avg       0.75      0.62      0.62       268
weighted avg       0.74      0.72      0.68       268



In [ ]:
# SVM 커널 파라미터 조정

# 커널 파라미터 rbf , C = 0.1, gamma = 0.1
sv = svm.SVC(kernel = 'rbf')

# 커널 파라미터 linear, C = 1, gamma = 0.1
sv = svm.SVC(kernel = 'linear', C = 1, gamma = 0.1)

**로지스틱 회귀분석**

In [51]:
# 로지스틱 회귀분석 : LogisticRegression()

lr = LogisticRegression()
lr.fit(x_train, y_train)

pred = lr.predict(x_test)

acc = accuracy_score(y_test, pred)

print(acc)

0.8134328358208955


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


**랜덤포레스트(분류)**

In [53]:
# 랜덤포레스트(분류) : RandomForestClassifier(n_estimator = 50, max_depth = 3, random_state = 20)

rf = RandomForestClassifier(n_estimators = 50, max_depth = 3, random_state = 20)
rf.fit(x_train, y_train)

pred = rf.predict(x_test)

acc = accuracy_score(y_test, pred)

print(acc)

0.8097014925373134
